#!/usr/bin/env python3
"""Generate gbt9704-layout.def from gbt9704-layout.json.

Converts layout parameters into LaTeX constant definitions that
the gbt9704.cls document class reads at compile time.

Usage:
    python3 tools/json2def.py gbt9704/gbt9704-layout.json > gbt9704/gbt9704-layout.def
"""

import json
import sys
from pathlib import Path


HEADER = """\
% gbt9704-layout.def — auto-generated from gbt9704-layout.json
% DO NOT EDIT THIS FILE. Edit the JSON and regenerate.
% Generator: tools/json2def.py
\\makeatletter
"""

FOOTER = "\\makeatother\n"


def escape(value: str) -> str:
    """Escape TeX special chars in a string value."""
    return value


def _to_camel(key: str) -> str:
    """Convert snake_case key to camelCase for LaTeX-safe macro names.

    LaTeX treats '_' as subscript, so macro names cannot contain underscores
    (outside of \\ExplSyntaxOn). We convert foo_bar → fooBar.
    """
    parts = key.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def _macro_name(section: str, key: str) -> str:
    """Build a LaTeX-safe macro name from section and key.

    Example: ('header_org', 'font_size') → 'gbt@layout@headerOrg@fontSize'
    """
    sec_safe = _to_camel(section)
    key_safe = _to_camel(key)
    return f"gbt@layout@{sec_safe}@{key_safe}"


def def_latex(name: str, value: str) -> str:
    """Emit a LaTeX \\def command."""
    # Wrap value that contains backslashes in braces to prevent early expansion
    return f"\\def\\{name}{{{value}}}"


def generate(json_path: str) -> str:
    """Read JSON and generate LaTeX constant definitions."""
    data = json.loads(Path(json_path).read_text(encoding="utf-8"))
    lines = [HEADER]

    # ── Colors ──
    colors = data.get("colors", {})
    for key, spec in colors.items():
        model = spec.get("model", "RGB")
        vals = spec.get("value", [0, 0, 0])
        val_str = ",".join(str(v) for v in vals)
        lines.append(def_latex(f"gbt@layout@color@{key}@model", model))
        lines.append(def_latex(f"gbt@layout@color@{key}@value", val_str))

    # ── Section-based parameters ──
    sections = [
        "header_org", "header_number", "redline", "title",
        "mainreceiver", "body", "signature", "signdate",
        "page_number",
    ]

    for sec in sections:
        spec = data.get(sec, {})
        for key, val in spec.items():
            if key == "description":
                continue
            if isinstance(val, dict):
                # Nested heading specs (h1/h2/h3)
                for sub_key, sub_val in val.items():
                    name = f"{_macro_name(sec, key)}@{sub_key}"
                    lines.append(def_latex(name, str(sub_val)))
            else:
                lines.append(def_latex(_macro_name(sec, key), str(val)))

    lines.append(FOOTER)
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: json2def.py <gbt9704-layout.json>", file=sys.stderr)
        sys.exit(1)
    print(generate(sys.argv[1]))
